### ISSUE TITLE
Wrap long code lines for readability

### ISSUE THREAD

**Issue by marcelwillis3** [mcarrington1/image-portal-service#30]
Hey M.J.,

Great project so far! I had a difficult time trying to find issues during my review.

One thing I found is some functions in your API code that require multiple input parameters may be too long for readability. An example of this is below:
https://github.com/mcarrington1/image-portal-service/blob/999c30b94c60334c36e8017950d3e73eb55dbef4/src/main/java/com/image/portal/api/AlbumApi.java#L104

If possible, the long lines could be wrapped at the commas, similar to how you did here:
https://github.com/mcarrington1/image-portal-service/blob/999c30b94c60334c36e8017950d3e73eb55dbef4/src/main/java/com/image/portal/api/AlbumsApi.java#L36-L39

**Comment by mj-carrington** [comment]
Thank you so much for the feedback. I believe that my IDE can help with some of this wrapping via a built-in linter. I'm going to pull in this story so I can work on it next week.
